### ISSUE TITLE
Create web-app to show the Fellowbook data

### ISSUE THREAD

**Issue by shu8** [MLH-Fellowship/0.2.1-fellowbook#1]
- [x] With the use of Reactjs and Bable.js Create an interface to query aws-amplify API to show data quried.

Steps:
- [x] Create React starter app Project
- [x] Create Header Component
- [x] Create a Search that will be used to search for data
- [x] Create a Card Component which will be used to populate datas fetched.
- [x] Create a basic UI with a dummy data
- [x] Fetch data from aws-amplify API
- [x] Implement the search component to fetch data
- [x] Implement Filter on the Search to filter data based on the pod names
- [x] Implementation of hover effect that displays data

**Comment by kendevops** [comment]
Implemented all that was assigned.
