### ISSUE TITLE
Create Discord bot to integrate Fellowbook data with Discord

### ISSUE THREAD

**Issue by shu8** [MLH-Fellowship/0.2.1-fellowbook#2]
Create a Discord bot that fetches data from AWS Amplify and shows it in the MLH Discord server.

- [x] Create bot
- [x] Have bot reply to command based on user requested /gimme (pending fetch from AWS)
- [x] Deploy bot on Heroku or similar service
- [x] Get authorization from MLH admins to add bot to MLH Discord server

**Comment by ivov** [comment]
Only authorization remaining. Once we get the DB populated, I'll test it out with various users and ask MLH for permission.

**Comment by shu8** [comment]
Deployed & merged
