### ISSUE TITLE
Setup REST API and DB with AWS Amplify

### ISSUE THREAD

**Issue by shu8** [MLH-Fellowship/0.2.1-fellowbook#3]
- [x] create amazon AWS account
- [x] install CLI
- [x] authorise CLI
- [x] init amplify project `amplify init`
- [x] add amplify storage (db) `amplify add storage`
- [x] setup database scheme
- [x] add amplify REST API `amplify add api`
- [x] connect amplify db to amplify REST API

**Resources**
- https://aws-amplify.github.io/docs/js/tutorials/building-react-native-apps/

**Comment by shu8** [comment]
To elaborate, for the REST API we make, we'll need something like:

- `/get-users[/id]`
- `/add-user`
- `/edit-user`
- `/delete-user` (although this may be optional because in general we won't want to delete a Fellow!)

**Comment by shu8** [comment]
We should also probably add some authentication to the API so only Fellows can use it. This could be as simple as making them login with GitHub API and see if they are a member of the org?

Any thoughts @kendevops @ivov?

**Comment by shu8** [comment]
✅ Created AWS account and installed CLI

**Comment by kendevops** [comment]
Yes that's what i found out, We should use Github Login with Github API.

**Comment by shu8** [comment]
Currently having troubles finding out how to use GitHub authorisation with the AWS auth flow.

Ideally we have users login with GitHub, we check that they are in the MLH Fellowship org, and if they are then allow access to the API, and if not then show an error message.

https://docs.amplify.aws/lib/auth/social/q/platform/js#full-react-sample seems to suggest that a social sign in is possible, but by default they only have Facebook and Google.

I found https://docs.aws.amazon.com/cognito/latest/developerguide/cognito-user-pools-identity-provider.html but in Step 2 I can't see an 'Identity Providers' option in the sidebar.

Will keep researching...

**Comment by shu8** [comment]
Also found this article: https://docs.aws.amazon.com/cognito/latest/developerguide/external-identity-providers.html

which shows the only external providers it supports are providers with Open ID or with SAML enabled, but as far as I can tell, what we want is just to use the OAuth GitHub login process

**Comment by kendevops** [comment]
So what do you propose? Should we just use the Members which doesn't need Authentication?

**Comment by shu8** [comment]
I think for now we could try to use no authentication? at the end of the day, all this information is public anyway so the authentication doesn't add too much to the project anyway?

I've also asked on the fellowship discord channel to see if anyone else could help, but for now I'm going to just try get the API and DB working properly!

**Comment by kendevops** [comment]
Alright then, so i can just work on fetching the members and rendering it to the UI.

**Comment by shu8** [comment]
Wait actually, the authentication would be required to get Fellows who don't have the organisation listed as public, but I think for now we can focus on getting it working for people who do have it public (I think most of the members)?

**Comment by shu8** [comment]
Yeah that sounds good! But I think the webapp will fetch the members from the intermediate API we create that stores the users and their data?

**Comment by kendevops** [comment]
Yes i know i will be fetching from the API provided by you

**Comment by shu8** [comment]
okay awesome! 🙂

**Comment by shu8** [comment]
So, had a few problems today:

- spent a few hours on researching using GitHub OAuth with the Amplify auth module. I think I was going down a rabbit hole so left it
- spent some time figuring out a 'Missing Authorisation Token' error when calling certain API endpoints, I think it's something to do with the endpoint not being defined in /aws-backend/amplify/backend/api/fellowbookapi/api-params.json - so if this happens again, check there!

I had a look in the AWS dev console and it looks like there's an authorisation option which passes the data to another lambda function. I feel like this will work for the GitHub auth, so will try this ASAP. 

For now, will open a PR to get this merged in hopefully!
