### ISSUE TITLE
Create README.md and LICENSE.md

### ISSUE THREAD

**Issue by shu8** [MLH-Fellowship/0.2.1-fellowbook#4]
We need a comprehensive README and need to decide on a license for this project.

At a minimum, the README needs to contain:
- overview of the project
- screenshots/GIFs of the discord bot
- screenshot of the web app
- dev setup instructions (how to get started with contributing)

**Comment by ivov** [comment]
Latest guidelines: https://docs.google.com/document/d/19T1QaYzP15zGakOZ7NTuAZd2WjemVFJUqq505iwfoLI/edit

**Comment by shu8** [comment]
Completed as of https://github.com/MLH-Fellowship/0.2.1-fellowbook/commit/99bd4d0b5060939eb34676f7494e4f9a6f78a81c, https://github.com/MLH-Fellowship/0.2.1-fellowbook/commit/082896290134dcd816c26c132d15e96cc7ccd714, https://github.com/MLH-Fellowship/0.2.1-fellowbook/commit/d9a17562ff233d57abdb38183d5a813b38c32f69
