### ISSUE TITLE
Create initial script to fetch org data from GitHub API

### ISSUE THREAD

**Issue by shu8** [MLH-Fellowship/0.2.1-fellowbook#5]
See https://developer.github.com/v3/orgs/members/ for details on the API endpoint we will need to use to get the MLH-Fellowship GitHub organisation members.

Looks like we need to be authorised as a member of the organisation to get the 'hidden' members too - so one of us will need to login via the GitHub API to get that authorisation!

**Comment by ivov** [comment]
Implemented in commit https://github.com/MLH-Fellowship/0.2.1-fellowbook/commit/25e24539b61a7e7b2edc95fa9fec11453aff00e4
